title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: Markdown toot    # the name of the repository when it is created for the learner
  repo: Write-the-Learning-Lab    # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond # the type of action, full list at https://lab.github.com/docs/actions/
  with: 01_first-response.md
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: The beginning
- title: In the beginning # the title of the step, shown to the learner in the course progress page
  description: The start of the course. # a description of the step, shown to the learner in the course progress page
  event: pull_request # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 2: After the beginning
# - title: After starting # the title of the step, shown to the learner in the course progress page
#  description: The tutorial on the second step # a description of the step, shown to the learner in the course progress page
#  event: push # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: The middle
# - title: In the middling # the title of the step, shown to the learner in the course progress page
#  description: The third step # a description of the step, shown to the learner in the course progress page
#  event: pull_request.synchronize # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: The after middle step
# - title: The after middle # the title of the step, shown to the learner in the course progress page
#  description: Middling to afterwards. # a description of the step, shown to the learner in the course progress page
#  event: status # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: The final step
# - title: Endings # the title of the step, shown to the learner in the course progress page
#  description: The final step tutorial. # a description of the step, shown to the learner in the course progress page
#  event: issue_commented.created # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

